version: '3.7'

services:

  api:
    build: server/petiza
    depends_on:
      - mongo
      - mssql
    ports:
    - 5042:80
    networks:
      - petiza
    environment:
      - "mongoConnection__server=mongodb://mongo:27017/petiza"

  mongo:
    image: mongo:latest
    ports:
    - 27018:27017
    networks:
      - petiza

  mssql:
    image: 'microsoft/mssql-server-linux'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - './drive:/var/opt/mssql'
  
networks:
  petiza: