version: '3.7'

services:

  mssql:
    image: 'microsoft/mssql-server-linux'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - './drive:/var/opt/mssql'

  api:
    build: server/petiza
    depends_on:
      - mssql
    ports:
    - 5042:80
    networks:
      - petiza
  
networks:
  petiza: