version: '3.7'

services:

  api:
    build: server/petiza
    depends_on:
      - mongo
    ports:
    - 5042:80
    networks:
      - petiza
    environment:
      - "mongoConnection__server=mongodb://mongo:27017/petiza"

  mongo:
    image: mongo:latest
    ports:
    - 27018:27017
    networks:
      - petiza

networks:
  petiza: